### ISSUE TITLE
Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by MotalibHossain** [MotalibHossain/iTechEys#5]
when I go to run this project in GitHub codespace then shows this problem. but in Django setting file cross-domain code is ok.

![2023-01-19_114540](https://user-images.githubusercontent.com/52135729/226302902-187ab179-874b-45ce-bca9-2f10b2ef59f2.png)

**Comment by Rashed360** [comment]
Check if works,
![image](https://user-images.githubusercontent.com/29564029/229367765-6cfc40d4-20f6-43cb-b3f0-627b0c36c97c.png)
